import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class First50
{
    private static final Logger logger = LoggerFactory.getLogger ( First50.class );
    private static final Helpers helpers = new Helpers();

    public First50 () {}

    /**
     * If we list all the natural numbers below 10 that are multiple of 3 or 5, we get 3, 5, 6, and 9.
     * The sum of these multiples is 23.
     * Find the sum of all the multiples of 3 or 5 below 1000.
     */
    @Test
    public void Problem1 ()
    {
        int sum = 0;
        for ( int i = 999; i > 0; i-- )
        {
            if ( i % 3 == 0 || i % 5 == 0 ) sum += i;
        }
        logger.info ( "Problem 1 (Multiples of 3 or 5): The sum of all multiples of 3 or 5 below 1000 is {}", sum );
    }

    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
     * the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     * find the sum of the even-valued terms.
     */
    @Test
    public void Problem2 ()
    {
        int sum = 2, x = 1, y = 2; // Sum starts at 2 because 2 is a starting value less than four million which is even
        boolean counter = true;
        while ( x < 4000000 && y < 4000000 )
        {
            int next = x + y;
            if ( next % 2 == 0 ) sum += next;
            if ( counter )
            {
                x = next;
            }
            else
            {
                y = next;
            }
            counter = !counter;
        }
        logger.info ( "Problem 2 (Even Fibonacci Numbers): The sum of even-valued terms of the Fibonacci sequence less than 4 Million is {}", sum );
    }

    /**
     * The prime factors of 13195 are 5, 7, 13, 29
     * What is the largest prime factor of the number 600851475143?
     */
    @Test
    public void Problem3 ()
    {
        long number = 600851475143L;
        List<Long> factors = new ArrayList <>();

        for ( long i = 2; i < Math.sqrt ( number ); i++ )
        {
            if ( number % i == 0 ) {
                if ( helpers.isPrime ( i )) factors.add ( i );
                number = number / i;
                if ( helpers.isPrime ( number )) factors.add ( number );
                i = 2;
            }
        }

        AtomicLong largest = new AtomicLong ();
        factors.forEach ( factor -> { if ( factor > largest.get ()) largest.set ( factor ); } );
        logger.info ( "Problem 3 (Largest Prime Factor): The largest prime factor of {} is {}", "600851475143", largest );
    }

    /**
     * A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit
     * numbers is 9009 = 91 x 99.
     * Find the largest palindrome made from the product of two 3-digit numbers
     */
    @Test
    public void Problem4 ()
    {
        int largest = 0, number1 = 0, number2 = 0;

        for ( int testA = 999; testA >= 100; testA-- )
        {
            for ( int testB = testA; testB >= 100; testB-- )
            {
                int result = testA * testB;
                if ( result < largest ) break;
                if ( result > largest && helpers.isPalindromic ( result ))
                {
                    largest = result;
                    number1 = testA;
                    number2 = testB;
                }
            }
        }

        logger.info ( "Problem 4 (Largest Palindrome Product): The largest 3-digit palindromic number is {}, made up from {} and {}", largest, number1, number2 );
    }

    /**
     * 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
     * What is the smallest number that is evenly divisible by all of the numbers from 1 to 20?
     */
    @Test
    public void Problem5 ()
    {
        int highestNumber = 20;
        boolean found = false;

        while ( !found )
        {
            int counter = 0;
            for ( int i = 20; i >= 1; i-- )
            {
                if ( highestNumber % i == 0 ) counter++;
                else break;
            }
            if ( counter == 20 ) found = true;
            else highestNumber += 20;
        }

        logger.info ( "Problem 5 (Smallest Multiple): The smallest positive number evenly divisible by all numbers to 20 is {}", highestNumber);
    }

    /**
     * The sum of the squares of the first ten natural numbers is, 1^2 + 2^2 + [...] + 10^2 = 385
     * The square of the sum of the first ten natural numbers is (1 + 2 + [...] + 10)^2 = 55^2 == 3025
     * Hence the difference between the sum of the squares of the first ten natural numbers of the square of the sum is
     * 3025 - 3855 = 2640
     * Find te difference between the sum of the squares of the first one hundred natural numbers and the square of the sum
     */
    @Test
    public void Problem6 ()
    {
        int sumSquares = 0, squaredSum = 0;
        for ( int i = 1; i <= 100; i++ ) { sumSquares += i * i; squaredSum += i; }
        squaredSum *= squaredSum;
        logger.info ( "The difference between the sum of squares and the square of the sum is {}", squaredSum - sumSquares);
    }

    /**
     * By listing the first six prime numbers: 2, 3, 5, 7, 11, 13, we can see that the 6th prime is 13.
     * What is the 10,001st prime number?
     */
    @Test
    public void Problem7 ()
    {
        boolean found = false;
        // 2 is prime, by starting at 3 it only needs to check off numbers so is more efficient
        int targetNumber = 3, counter = 1;
        while ( !found )
        {
            if ( helpers.isPrime ( targetNumber )) { counter += 1; }
            if ( counter == 10001 ) found = true;
            else targetNumber += 2;
        }
        logger.info ( "The 10,001st prime number is {}", targetNumber );
    }
}
