import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class First50
{
    private static final Logger logger = LoggerFactory.getLogger ( First50.class );
    private static final Helpers helpers = new Helpers();

    public First50 () {}

    /**
     * If we list all the natural numbers below 10 that are multiple of 3 or 5, we get 3, 5, 6, and 9.
     * The sum of these multiples is 23.
     * Find the sum of all the multiples of 3 or 5 below 1000.
     */
    @Test
    public void Problem1 ()
    {
        int sum = 0;
        for ( int i = 999; i > 0; i-- )
        {
            if ( i % 3 == 0 || i % 5 == 0 ) sum += i;
        }
        logger.info ( "Problem 1 (Multiples of 3 or 5): The sum of all multiples of 3 or 5 below 1000 is {}", sum );
    }

    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
     * the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     * find the sum of the even-valued terms.
     */
    @Test
    public void Problem2 ()
    {
        int sum = 2, x = 1, y = 2; // Sum starts at 2 because 2 is a starting value less than four million which is even
        boolean counter = true;
        while ( x < 4000000 && y < 4000000 )
        {
            int next = x + y;
            if ( next % 2 == 0 ) sum += next;
            if ( counter )
            {
                x = next;
            }
            else
            {
                y = next;
            }
            counter = !counter;
        }
        logger.info ( "Problem 2 (Even Fibonacci Numbers): The sum of even-valued terms of the Fibonacci sequence less than 4 Million is {}", sum );
    }

    /**
     * The prime factors of 13195 are 5, 7, 13, 29
     * What is the largest prime factor of the number 600851475143?
     */
    @Test
    public void Problem3 ()
    {
        long number = 600851475143L;
        List<Long> factors = new ArrayList <>();

        for ( long i = 2; i < Math.sqrt ( number ); i++ )
        {
            if ( number % i == 0 ) {
                if ( helpers.isPrime ( i )) factors.add ( i );
                number = number / i;
                if ( helpers.isPrime ( number )) factors.add ( number );
                i = 2;
            }
        }

        AtomicLong largest = new AtomicLong ();
        factors.forEach ( factor -> { if ( factor > largest.get ()) largest.set ( factor ); } );
        logger.info ( "Problem 3 (Largest Prime Factor): The largest prime factor of {} is {}", "600851475143", largest );
    }

    /**
     * A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit
     * numbers is 9009 = 91 x 99.
     * Find the largest palindrome made from the product of two 3-digit numbers
     */
    @Test
    public void Problem4 ()
    {
        int largest = 0, number1 = 0, number2 = 0;

        for ( int testA = 999; testA >= 100; testA-- )
        {
            for ( int testB = testA; testB >= 100; testB-- )
            {
                int result = testA * testB;
                if ( result < largest ) break;
                if ( result > largest && helpers.isPalindromic ( result ))
                {
                    largest = result;
                    number1 = testA;
                    number2 = testB;
                }
            }
        }

        logger.info ( "Problem 4 (Largest Palindrome Product): The largest 3-digit palindromic number is {}, made up from {} and {}", largest, number1, number2 );
    }

    /**
     * 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
     * What is the smallest number that is evenly divisible by all of the numbers from 1 to 20?
     */
    @Test
    public void Problem5 ()
    {
        int highestNumber = 20;
        boolean found = false;

        while ( !found )
        {
            int counter = 0;
            for ( int i = 20; i >= 1; i-- )
            {
                if ( highestNumber % i == 0 ) counter++;
                else break;
            }
            if ( counter == 20 ) found = true;
            else highestNumber += 20;
        }

        logger.info ( "Problem 5 (Smallest Multiple): The smallest positive number evenly divisible by all numbers to 20 is {}", highestNumber);
    }

    /**
     * The sum of the squares of the first ten natural numbers is, 1^2 + 2^2 + [...] + 10^2 = 385
     * The square of the sum of the first ten natural numbers is (1 + 2 + [...] + 10)^2 = 55^2 == 3025
     * Hence the difference between the sum of the squares of the first ten natural numbers of the square of the sum is
     * 3025 - 3855 = 2640
     * Find te difference between the sum of the squares of the first one hundred natural numbers and the square of the sum
     */
    @Test
    public void Problem6 ()
    {
        int sumSquares = 0, squaredSum = 0;
        for ( int i = 1; i <= 100; i++ ) { sumSquares += i * i; squaredSum += i; }
        squaredSum *= squaredSum;
        logger.info ( "The difference between the sum of squares and the square of the sum is {}", squaredSum - sumSquares );
    }

    /**
     * By listing the first six prime numbers: 2, 3, 5, 7, 11, 13, we can see that the 6th prime is 13.
     * What is the 10,001st prime number?
     */
    @Test
    public void Problem7 ()
    {
        boolean found = false;
        // 2 is prime, by starting at 3 it only needs to check off numbers so is more efficient
        int targetNumber = 3, counter = 1;
        while ( !found )
        {
            if ( helpers.isPrime ( targetNumber )) { counter += 1; }
            if ( counter == 10001 ) found = true;
            else targetNumber += 2;
        }
        logger.info ( "The 10,001st prime number is {}", targetNumber );
    }

    /**
     * The four adjacent digits in the 1000-digit number that have the greatest product are 9 x 9 x 8 x 9 = 5832
     * 73167176531330624919225119674426574742355349194934
     * 96983520312774506326239578318016984801869478851843
     * 85861560789112949495459501737958331952853208805511
     * 12540698747158523863050715693290963295227443043557
     * 66896648950445244523161731856403098711121722383113
     * 62229893423380308135336276614282806444486645238749
     * 30358907296290491560440772390713810515859307960866
     * 70172427121883998797908792274921901699720888093776
     * 65727333001053367881220235421809751254540594752243
     * 52584907711670556013604839586446706324415722155397
     * 53697817977846174064955149290862569321978468622482
     * 83972241375657056057490261407972968652414535100474
     * 82166370484403199890008895243450658541227588666881
     * 16427171479924442928230863465674813919123162824586
     * 17866458359124566529476545682848912883142607690042
     * 24219022671055626321111109370544217506941658960408
     * 07198403850962455444362981230987879927244284909188
     * 84580156166097919133875499200524063689912560717606
     * 05886116467109405077541002256983155200055935729725
     * 71636269561882670428252483600823257530420752963450
     * Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?
     */
    @Test
    public void Problem8 ()
    {
        String numberAsString = "7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450";
        char [] numberAsCharArray = numberAsString.toCharArray ();
        long greatestProduct = 0;

        for ( int i = 0; i <= numberAsString.length () - 13; i++ )
        {
            List < Long > numbers = new ArrayList <>();
            for ( int x = i; x < i + 13; x++ ) numbers.add ( Long.parseLong ( String.valueOf ( numberAsCharArray [ x ])));
            long tempProduct = 1;
            for ( Long number : numbers ) tempProduct *= number;
            if ( tempProduct > greatestProduct ) greatestProduct = tempProduct;
        }

        logger.info ( "The greatest product of thirteen adjacent digits in the 1000-digit number, is {}", greatestProduct );
    }

    /**
     * A Pythagorean triplet is a set of three natural numbers, a < b < c, for which, a^2 + b^2 = c^2.
     * For example, 3^2 + 4^2 = 9 ++ 16 = 25 = 5^2
     * There exists exactly one Pythagorean triplet for which a + b + c = 1000.
     * Find product abc
     */
    @Test
    public void Problem9 ()
    {
        for ( int a = 1; a < 1000; a++ )
        {
            for ( int b = 1; b < 1000; b++ )
            {
                int squaredResult = a * a + b * b;
                double c = Math.sqrt ( squaredResult );
                if ( a + b + c == 1000 )
                {
                    logger.info ( "The product of the triplet where a + b + c = 1000 is {}", ( long ) ( a * b * c ));
                    return;
                }
            }
        }
    }

    /**
     * The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17
     * Find the sum of all primes below two million.
     */
    @Test
    public void Problem10 ()
    {
        long sumOfPrimes = 2;
        for ( int counter = 3; counter < 2000000; counter += 2 )
        {
            if ( helpers.isPrime ( counter )) sumOfPrimes += counter;
        }
        logger.info ( "The sum of all the primes below two million is {}", sumOfPrimes );
    }
}
