import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class First50
{
    private static final Logger logger = LoggerFactory.getLogger ( First50.class );
    private static final Helpers helpers = new Helpers();

    public First50 () {}

    /**
     * If we list all the natural numbers below 10 that are multiple of 3 or 5, we get 3, 5, 6, and 9.
     * The sum of these multiples is 23.
     * Find the sum of all the multiples of 3 or 5 below 1000.
     */
    @Test
    public void Problem1 ()
    {
        int sum = 0;
        for ( int i = 999; i > 0; i-- )
        {
            if ( i % 3 == 0 || i % 5 == 0 ) sum += i;
        }
        logger.info ( "Problem 1 (Multiples of 3 or 5): The sum of all multiples of 3 or 5 below 1000 is {}", sum );
    }

    /**
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
     * the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     * find the sum of the even-valued terms.
     */
    @Test
    public void Problem2 ()
    {
        int sum = 2, x = 1, y = 2; // Sum starts at 2 because 2 is a starting value less than four million which is even
        boolean counter = true;
        while ( x < 4000000 && y < 4000000 )
        {
            int next = x + y;
            if ( next % 2 == 0 ) sum += next;
            if ( counter )
            {
                x = next;
            }
            else
            {
                y = next;
            }
            counter = !counter;
        }
        logger.info ( "Problem 2 (Even Fibonacci Numbers): The sum of even-valued terms of the Fibonacci sequence less than 4 Million is {}", sum );
    }

    /**
     * The prime factors of 13195 are 5, 7, 13, 29
     * What is the largest prime factor of the number 600851475143?
     */
    @Test
    public void Problem3 ()
    {
        long number = 600851475143L;
        List<Long> factors = new ArrayList <>();

        for ( long i = 2; i < Math.sqrt ( number ); i++ )
        {
            if ( number % i == 0 ) {
                if ( helpers.isPrime ( i )) factors.add ( i );
                number = number / i;
                if ( helpers.isPrime ( number )) factors.add ( number );
                i = 2;
            }
        }

        AtomicLong largest = new AtomicLong ();
        factors.forEach ( factor -> { if ( factor > largest.get ()) largest.set ( factor ); } );
        logger.info ( "Problem 3 (Largest Prime Factor): The largest prime factor of {} is {}", "600851475143", largest );
    }

    /**
     * A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit
     * numbers is 9009 = 91 x 99.
     * Find the largest palindrome made from the product of two 3-digit numbers
     */
    @Test
    public void Problem4 ()
    {
        int largest = 0, number1 = 0, number2 = 0;

        for ( int testA = 999; testA >= 100; testA-- )
        {
            for ( int testB = testA; testB >= 100; testB-- )
            {
                int result = testA * testB;
                if ( result < largest ) break;
                if ( result > largest && helpers.isPalindromic ( result ))
                {
                    largest = result;
                    number1 = testA;
                    number2 = testB;
                }
            }
        }

        logger.info ( "Problem 4 (Largest Palindrome Product): The largest 3-digit palindromic number is {}, made up from {} and {}", largest, number1, number2 );
    }

    /**
     * 2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
     * What is the smallest number that is evenly divisible by all of the numbers from 1 to 20?
     */
    @Test
    public void Problem5 ()
    {
        int highestNumber = 20;
        boolean found = false;

        while ( !found )
        {
            int counter = 0;
            for ( int i = 20; i >= 1; i-- )
            {
                if ( highestNumber % i == 0 ) counter++;
                else break;
            }
            if ( counter == 20 ) found = true;
            else highestNumber += 20;
        }

        logger.info ( "Problem 5 (Smallest Multiple): The smallest positive number evenly divisible by all numbers to 20 is {}", highestNumber);
    }

    /**
     * The sum of the squares of the first ten natural numbers is, 1^2 + 2^2 + [...] + 10^2 = 385
     * The square of the sum of the first ten natural numbers is (1 + 2 + [...] + 10)^2 = 55^2 == 3025
     * Hence the difference between the sum of the squares of the first ten natural numbers of the square of the sum is
     * 3025 - 3855 = 2640
     * Find te difference between the sum of the squares of the first one hundred natural numbers and the square of the sum
     */
    @Test
    public void Problem6 ()
    {
        int sumSquares = 0, squaredSum = 0;
        for ( int i = 1; i <= 100; i++ ) { sumSquares += i * i; squaredSum += i; }
        squaredSum *= squaredSum;
        logger.info ( "The difference between the sum of squares and the square of the sum is {}", squaredSum - sumSquares );
    }

    /**
     * By listing the first six prime numbers: 2, 3, 5, 7, 11, 13, we can see that the 6th prime is 13.
     * What is the 10,001st prime number?
     */
    @Test
    public void Problem7 ()
    {
        boolean found = false;
        // 2 is prime, by starting at 3 it only needs to check off numbers so is more efficient
        int targetNumber = 3, counter = 1;
        while ( !found )
        {
            if ( helpers.isPrime ( targetNumber )) { counter += 1; }
            if ( counter == 10001 ) found = true;
            else targetNumber += 2;
        }
        logger.info ( "The 10,001st prime number is {}", targetNumber );
    }

    /**
     * The four adjacent digits in the 1000-digit number that have the greatest product are 9 x 9 x 8 x 9 = 5832
     * 73167176531330624919225119674426574742355349194934
     * 96983520312774506326239578318016984801869478851843
     * 85861560789112949495459501737958331952853208805511
     * 12540698747158523863050715693290963295227443043557
     * 66896648950445244523161731856403098711121722383113
     * 62229893423380308135336276614282806444486645238749
     * 30358907296290491560440772390713810515859307960866
     * 70172427121883998797908792274921901699720888093776
     * 65727333001053367881220235421809751254540594752243
     * 52584907711670556013604839586446706324415722155397
     * 53697817977846174064955149290862569321978468622482
     * 83972241375657056057490261407972968652414535100474
     * 82166370484403199890008895243450658541227588666881
     * 16427171479924442928230863465674813919123162824586
     * 17866458359124566529476545682848912883142607690042
     * 24219022671055626321111109370544217506941658960408
     * 07198403850962455444362981230987879927244284909188
     * 84580156166097919133875499200524063689912560717606
     * 05886116467109405077541002256983155200055935729725
     * 71636269561882670428252483600823257530420752963450
     * Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?
     */
    @Test
    public void Problem8 ()
    {
        String numberAsString = "7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450";
        char [] numberAsCharArray = numberAsString.toCharArray ();
        long greatestProduct = 0;

        for ( int i = 0; i <= numberAsString.length () - 13; i++ )
        {
            List < Long > numbers = new ArrayList <>();
            for ( int x = i; x < i + 13; x++ ) numbers.add ( Long.parseLong ( String.valueOf ( numberAsCharArray [ x ])));
            long tempProduct = 1;
            for ( Long number : numbers ) tempProduct *= number;
            if ( tempProduct > greatestProduct ) greatestProduct = tempProduct;
        }

        logger.info ( "The greatest product of thirteen adjacent digits in the 1000-digit number, is {}", greatestProduct );
    }

    /**
     * A Pythagorean triplet is a set of three natural numbers, a < b < c, for which, a^2 + b^2 = c^2.
     * For example, 3^2 + 4^2 = 9 ++ 16 = 25 = 5^2
     * There exists exactly one Pythagorean triplet for which a + b + c = 1000.
     * Find product abc
     */
    @Test
    public void Problem9 ()
    {
        for ( int a = 1; a < 1000; a++ )
        {
            for ( int b = 1; b < 1000; b++ )
            {
                int squaredResult = a * a + b * b;
                double c = Math.sqrt ( squaredResult );
                if ( a + b + c == 1000 )
                {
                    logger.info ( "The product of the triplet where a + b + c = 1000 is {}", ( long ) ( a * b * c ));
                    return;
                }
            }
        }
    }

    /**
     * The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17
     * Find the sum of all primes below two million.
     */
    @Test
    public void Problem10 ()
    {
        long sumOfPrimes = 2;
        for ( int counter = 3; counter < 2000000; counter += 2 )
        {
            if ( helpers.isPrime ( counter )) sumOfPrimes += counter;
        }
        logger.info ( "The sum of all the primes below two million is {}", sumOfPrimes );
    }

    /**
     * In the 20 x 20 grid below, four numbers along a diagonal line have been marked with a period at the end.
     * 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
     * 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
     * 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
     * 52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
     * 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
     * 24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
     * 32 98 81 28 64 23 67 10 26. 38 40 67 59 54 70 66 18 38 64 70
     * 67 26 20 68 02 62 12 20 95 63. 94 39 63 08 40 91 66 49 94 21
     * 24 55 58 05 66 73 99 26 97 17 78. 78 96 83 14 88 34 89 63 72
     * 21 36 23 09 75 00 76 44 20 45 35 14. 00 61 33 97 34 31 33 95
     * 78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
     * 16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
     * 86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
     * 19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
     * 04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
     * 88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
     * 04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
     * 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
     * 20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
     * 01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48
     *
     * The product of these numbers is 26 x 63 x 78 x 14 = 1788696.
     * What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally)
     * in the 20 x 20 grid?
     */
    @Test
    public void Problem11 ()
    {
        // Initialise Data in array of arrays to replicate a grid
        int [] row0 = { 8, 2, 22, 97, 38, 15, 0, 40, 0, 75, 4, 5, 7, 78, 52, 12, 50, 77, 91, 8 };
        int [] row1 = { 49, 49, 99, 40, 17, 81, 18, 57, 60, 87, 17, 40, 98, 43, 69, 48, 4, 56, 62, 0 };
        int [] row2 = { 81, 49, 31, 73, 55, 79, 14, 29, 93, 71, 40, 67, 53, 88, 30, 3, 49, 13, 36, 65 };
        int [] row3 = { 52, 70, 95, 23, 4, 60, 11, 42, 69, 24, 68, 56, 1, 32, 56, 71, 37, 2, 36, 91 };
        int [] row4 = { 22, 31, 16, 71, 51, 67, 63, 89, 41, 92, 36, 54, 22, 40, 40, 28, 66, 33, 13, 80 };
        int [] row5 = { 24, 47, 32, 60, 99, 3, 45, 2, 44, 75, 33, 53, 78, 36, 84, 20, 35, 17, 12, 50 };
        int [] row6 = { 32, 98, 81, 28, 64, 23, 67, 10, 26, 38, 40, 67, 59, 54, 70, 66, 18, 38, 64, 70 };
        int [] row7 = { 67, 26, 20, 68, 2, 62, 12, 20, 95, 63, 94, 39, 63, 8, 40, 91, 66, 49, 94, 21 };
        int [] row8 = { 24, 55, 58, 5, 66, 73, 99, 26, 97, 17, 78, 78, 96, 83, 14, 88, 34, 89, 63, 72 };
        int [] row9 = { 21, 36, 23, 9, 75, 0, 76, 44, 20, 45, 35, 14, 0, 61, 33, 97, 34, 31, 33, 95 };
        int [] row10 = { 78, 17, 53, 28, 22, 75, 31, 67, 15, 94, 3, 80, 4, 62, 16, 14, 9, 53, 56, 92 };
        int [] row11 = { 16, 39, 5, 42, 96, 35, 31, 47, 55, 58, 88, 24, 0, 17, 54, 24, 36, 29, 85, 57 };
        int [] row12 = { 86, 56, 0, 48, 35, 71, 89, 7, 5, 44, 44, 37, 44, 60, 21, 58, 51, 54, 17, 58 };
        int [] row13 = { 19, 80, 81, 68, 5, 94, 47, 69, 28, 73, 92, 13, 86, 52, 17, 77, 4, 89, 55, 40 };
        int [] row14 = { 4, 52, 8, 83, 97, 35, 99, 16, 7, 97, 57, 32, 16, 26, 26, 79, 33, 27, 98, 66 };
        int [] row15 = { 88, 36, 68, 87, 57, 62, 20, 72, 3, 46, 33, 67, 46, 55, 12, 32, 63, 93, 53, 69 };
        int [] row16 = { 4, 42, 16, 73, 38, 25, 39, 11, 24, 94, 72, 18, 8, 46, 29, 32, 40, 62, 76, 36 };
        int [] row17 = { 20, 69, 36, 41, 72, 30, 23, 88, 34, 62, 99, 69, 82, 67, 59, 85, 74, 4, 36, 16 };
        int [] row18 = { 20, 73, 35, 29, 78, 31, 90, 1, 74, 31, 49, 71, 48, 86, 81, 16, 23, 57, 5, 54 };
        int [] row19 = { 1, 70, 54, 71, 83, 51, 54, 69, 16, 92, 33, 48, 61, 43, 52, 1, 89, 19, 67, 48 };
        int [][] rows = { row0, row1, row2, row3, row4, row5, row6, row7, row8, row9,
                row10, row11, row12, row13, row14, row15, row16, row17, row18, row19 };

        // { x, y } With x being column (index in row), and y being row (number)
        int [][] directions = {
                { 0, -1 }, // Up
                { 1, -1 }, // Up Right
                { 1, 0 }, // Right
                { 1, 1 }, // Down Right
                { 0, 1 }, // Down
                { -1, 1 }, // Down Left
                { -1, 0 }, // Left
                { -1, -1 } // Up Left
        };
        int greatestProduct = 0;

        for ( int y = 0; y < 20; y++ )
        {
            int [] row = rows [ y ];
            for ( int x = 0; x < 20; x++ )
            {
                outer:
                for ( int [] direction : directions )
                {
                    List < Integer > numbers = new ArrayList <>();
                    numbers.add ( row [ x ]);
                    int nx = x;
                    int ny = y;
                    while ( numbers.size () < 4 )
                    {
                        nx += direction [ 0 ];
                        ny += direction [ 1 ];
                        if ( nx >= 0 && ny >= 0 && nx < 20 && ny < 20 )
                        {
                            numbers.add ( rows [ ny ] [ nx ] );
                        } else
                        {
                            continue outer;
                        }
                    }
                    int productInDirection = numbers.get ( 0 ) * numbers.get ( 1 ) * numbers.get ( 2 ) * numbers.get ( 3 );
                    greatestProduct = Math.max ( productInDirection, greatestProduct );
                }
            }
        }

        logger.info ( "The greatest product of four adjacent numbers in the same direction in the grid is {}", greatestProduct );
    }

    /**
     * The sequence of triangle numbers is generated by adding the natural numbers.
     * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
     * The first ten terms would be:
     * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
     * Let us list the factors of the first seven triangle numbers:
     * 1: 1
     * 3: 1, 3
     * 6: 1, 2, 3, 6
     * 10: 1, 2, 5, 10
     * 15: 1, 3, 5, 15
     * 21: 1, 3, 7, 21
     * 28: 1, 2, 4, 7, 14, 28
     * We can see that 28 is the first triangle number to have over five divisors.
     * What is the value of the first triangle number to have over five hundred divisors?
     */
    @Test
    public void Problem12 ()
    {
        boolean found = false;
        int triangleNumber = 1;
        int fiveHundredDivisors = 0;
        while ( !found )
        {
            int total = 0;
            for ( int x = 1; x <= triangleNumber; x++ )
            {
                total += x;
            }
            if ( helpers.GetFactors ( total ).size () >= 500 )
            {
                fiveHundredDivisors = total;
                found = true;
            }
            triangleNumber++;
        }

        logger.info ( "The value of the first triangle number to have over five hundred divisors is {}", fiveHundredDivisors );
    }
}
